### ISSUE TITLE
扫描结果保存的文件名 是什么内容，以什么格式保存呢

### ISSUE THREAD

**Issue by LittleFlorence** [conwnet/wpa-dictionary#8]
使用命令：airodump-ng -w <扫描结果保存的文件名> -c <无线网络信道> --bssid <目标无线 AP 的硬件地址> <处于监听模式的网卡名称>

**Comment by conwnet** [comment]
输出的是 cap 格式文件

**Comment by LittleFlorence** [comment]
这条命令 -w 后面跟的的确是一个自己命名且不用设置格式的文件名而不是一个已经存在的文件。
